name: DisplayBuildTools
version: '${project.version}'
main: land.builders.displaybuildtools.DisplayBuildTools
api-version: 1.19
author: TWME
website: https://github.com/TWME-TW/UprightSlabTool
commands:
  displaybuildtools:
    permission: displaybuildtools.use
    aliases:
      - displaybuildtools
      - dbt
permissions:
  displaybuildtools.use:
    default: op
